### PR TITLE
Add `httpsAgent` option in  `ProfileService`.

### PR DESCRIPTION
**Pull request by tolson4**
Adds an option to `ProfileSerivce` to allow for an https agent to be passed in, cleans up and unifies a few stylistic issues.

### CODE REVIEW

**Comment by tolson4** [comment]
@davidlehn @dlongley @gannan08

**Review by dlongley — APPROVED** [review]
This seems ok to me -- provided that it matches our approach elsewhere to allow `web` libs to be used by node.js. I can't recall our pattern for dealing with adding `httpsAgent` to `web` libs. @davidlehn can you make sure this is right?

**Comment by JSAssassin** [comment]
@dlongley not sure if our pattern for dealing with httpsAgent has changed now or not but the last time it was removed(back in 2021 lol) was because of this - https://github.com/digitalbazaar/bedrock-web-profile/pull/16#discussion_r626135843.

**Comment by dlongley** [comment]
I do wonder if it's better to accept an `httpClient` instance to use instead.

**Comment by davidlehn** [comment]
I'm not sure we had a plan for this.  For the browser case, the code doesn't need an agent.  Some of the other bedrock-web-* packages can be made to work in node CLI tools, but it's not pretty.  I don't think we've had to use this package yet so I'm not sure of the issues here.

One solution basically involves faking being a browser in a controller manner.  I'm not sure it would work for general use though.  It required setting up a custom cookie jar per origin, use overrides for a custom ky fetch and Request, handling relative URLs properly, and maybe more.  A general redesign of some sort is likely needed to fix all that.

Ideally we'd have a common pattern for all the bedrock-web* packages that would allow easy default use in browsers, and much simpler use in node apps.

**Review by dlongley — CHANGES_REQUESTED** [review]
Yeah, I believe just adding an `httpsAgent` option is also likely to be insufficient -- as these libraries also assume a number of things are in play, including cookie storage and use, etc.

I think we need a more general solution to the problem that would create the desired environment as @davidlehn was mentioning -- otherwise, I wouldn't be surprised if we started having to add a bunch of little piecemeal patches here and there that would require devs to bring them all together. IOW, they'd reimplement the same `fetch` the browser is using but sort of smeared across all the APIs.

That implies to me that perhaps the right thing to do is make sure that the globally-used `fetch` is just appropriately setup in the environment that's running this code and other `web` libs -- rather than changing them all.

**Comment by tolson4** [comment]
This came about as part of a unit test effort we are working on for one of our bedrock applications. Adding `httpsAgent` was a first pass at trying to wire some things up to facilitate those tests. This ended up not being a workable solution, and was dropped for another approach.

@dlongley @davidlehn I'm going to go ahead and close this PR. Feel free to reopen if needed.

**Pull request closed without merging**
